### PR TITLE
Create -7-Reverse_Integer.c

### PR DESCRIPTION
**Pull request by FaheemorFAB**
Hacktober
Fixes issue  REVERSE INTEGER #73

### CODE REVIEW

**Comment by FaheemorFAB** [comment]
tell me how to structure it
plz

**Comment by Hsinha11** [comment]
put submission in a folder and add a readme file explaining the code , another file for the code ,
see the rest of the submissions and the structures

**Comment by FaheemorFAB** [comment]
Copy That

**Comment by FaheemorFAB** [comment]
merge it and i will fix them like patch 6..
This will be easier for me if you dont mind @Hsinha11

**Pull request merged**
